config/routes.rb
Resources::Application.routes.draw do

  resources :hangqingbaojias, only: [:index] do
    collection do 
      get "jiage_list"
      get "more_jiage_list"
      get "hangqing_list"
      get "dongtai_list"
      get "more_dongtai_list"
      get "comment"
    end
  end

  resources :jiages do 
    collection do 
      get "get_categories"
    end
  end

  resources :dongtais

  resources :hangqings

  resources :comments do
    collection do 
      get "list"
    end
  end

  resources :contacts

  resources :message_types

  resources :lanzis, only: [:index, :create, :destroy]

  resources :customer_types

  resources :customers

  resources :news

  resources :transaction_types

  resources :shangjidingzhis do 
    collection do
      get "list"
    end
  end

  resources :company_prices
  resources :jiaoyis, only: [:index, :show]
  resources :baojias, only: [:index]
  resources :hangqingbaojias, only: [:index]
  resources :zixuns, only: [:index] do 
    collection do
      get "list"
    end
  end

  get "home" => "home#index"
  get "shangbiao" => "home#shangbiao"
  get "shengming" => "home#shengming"
  get "services" => "home#services"
  get "privacy" => "home#privacy"
  get "ad" => "home#ad"
  get "lianxi" => "home#lianxi"
  get "recruit" => "home#recruit"
  get "guanggao_attachment" => "home#guanggao_attachment"
  get "search_home" => "home#search"
  get "search_by_tag_home" => "home#search_by_tag"
  get "admin" => "admin#index"

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_scope :user do
    get "bianji_mima", :to => "devise/registrations#bianji_mima"
    put "update_password", :to => "devise/registrations#update_password"
  end

  resources :regions, only: [:show]

  resources :countries, only: [:show]

  get 'verify_email_exist' => "users#verify_email_exist"
  get 'verify_username_exist' => "users#verify_username_exist"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get "entverify"
      put "verify"
      get "purview"
      get "entmember"
      put "member"
      get "home"
      get "info_and_image"
      get "edit_desc"
      put "update_desc"
      get "edit_image"
      get "edit_license"
    end
  end

  resources :transactions do
    member do
      get "images"
    end

    collection do
      get "tags"
      get "refresh"
    end

    member do
      get "change_transaction_type"
    end
  end

  delete "delete_transactions" => "transactions#destroy"

  resources :links

  resources :attachments do
    collection do
      post "upload"
    end
  end

  resources :categories, only: :show
  resources :company_price_categories, only: :show
  resources :articles
  resources :messages do
    collection do
      put "restore"
    end
  end

  constraints(Subdomain) do
    match '/' => 'member#home', as: "member_home"
    match '/member/show' => 'member#show'
    match '/member/contact' => 'member#contact'
    match '/member/transactions' => 'member#transactions'
    match '/member/transaction/:id' => 'member#transaction', as: "member_transaction"
    match '/member/news' => 'member#news'
    match '/member/message' => 'member#message'
    match '/member/news/:id' => 'member#new', as: "member_new"
  end

  root to: "home#index"

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:error).call(env) }  # 因为application.rb捕获不到rails路由错误，所以rails路由报错后指向application_controller.rb中的error action.

end

app/models/shangjidingzhi.rb
#coding: utf-8
require "will_paginate/array"

class Shangjidingzhi < ActiveRecord::Base
  belongs_to :user
  belongs_to :region
  belongs_to :city
  
  default_value_for :info_type, :all

  symbolize :info_type, in: [:supply, :seeking, :all]

  validates :keyword, presence: true

  attr_reader :email

  def address
    (address = [region.try(:name), city.try(:name)].join("  ")).blank? ? "无地区信息" : address
  end

  def is_send_email_text
    is_send_email ? "邮件提醒" : "无邮件提醒"
  end

  def transactions(limit = nil)
    t1 = Transaction.tagged_with(keyword, any: true, wild: true).limit(limit)
    t2 = Transaction.search_by_title_and_category(keyword).limit(limit)
    ts = [t1 + t2].flatten.uniq
    (limit.nil? ? ts : ts.slice(0, limit)).sort{|a, b| b.created_at <=> a.created_at}
  end

  def self.start_job
    users = User.find(Shangjidingzhi.where(is_send_email: true).group(:user_id).pluck(:user_id))
    Delayed::Job.enqueue(ShangjidingzhiJob.new(users))
  end

end

app/controllers/shangjidingzhis_controller.rb
#coding: utf-8

class ShangjidingzhisController < ApplicationController

  before_filter :authenticate_user!
  layout "admin", except: [:new, :edit]

  # GET /shangjidingzhis
  # GET /shangjidingzhis.json
  def index
    @shangjidingzhis = current_user.shangjidingzhis.paginate(page: params[:page], per_page: 15).order("created_at DESC")
  end

  # GET /shangjidingzhis/1
  # GET /shangjidingzhis/1.json
  def show
   
  end

  # GET /shangjidingzhis/new
  # GET /shangjidingzhis/new.json
  def new
    @shangjidingzhi = current_user.shangjidingzhis.new
  end

  # GET /shangjidingzhis/1/edit
  def edit
    @shangjidingzhi = current_user.shangjidingzhis.find(params[:id])
  end

  # POST /shangjidingzhis
  # POST /shangjidingzhis.json
  def create
    @shangjidingzhi = current_user.shangjidingzhis.new(params[:shangjidingzhi])
    if @shangjidingzhi.save
    redirect_to shangjidingzhis_path, notice: '商机定制成功.'
    else
      render action: "new"
    end
  end

  # PUT /shangjidingzhis/1
  # PUT /shangjidingzhis/1.json
  def update
    @shangjidingzhi = current_user.shangjidingzhis.find(params[:id])
    if @shangjidingzhi.update_attributes(params[:shangjidingzhi])
      redirect_to shangjidingzhis_path, notice: '商机定制成功.'
    else
      render action: "edit"
    end
  end

  # DELETE /shangjidingzhis/1
  # DELETE /shangjidingzhis/1.json
  def destroy
    @shangjidingzhi = current_user.shangjidingzhis.find(params[:id])
    @shangjidingzhi.destroy
    redirect_to shangjidingzhis_url
  end

  def list
    @shangjidingzhis = current_user.shangjidingzhis
    shangjidingzhi = @shangjidingzhis.find_by_id(params[:id] || @shangjidingzhis.first)
    @transactions = shangjidingzhi.nil? ? [] : shangjidingzhi.transactions.paginate(page: params[:page], per_page: 8) 
  end


end

app/helpers/shangjidingzhis_helper.rb
module ShangjidingzhisHelper
end

app/views/shangjidingzhis/_form.html.erb
<div class="weizhi">当前位置：<%= link_to "首页", home_path %> >  交易中心 &gt; <font color="#FF6600">订制报价</font></div>
<div class="gly_bottom">
  <div class="czmm_header">实时报价定制</div>
  <%= simple_form_for(@shangjidingzhi, html: {class: "validate_form"}) do |f| %>
    <div class="ht_bot">
      <div class="czmm_footer">
        <ul>
          <li class="fbxx_footer_zi4">
          <font color="#FF0000">*</font>关键字：
          </li>
          <li><%= f.input :keyword, input_html: {class: "validate[required] wenben11"}, label: false, wrapper: false %></li>
        </ul>
        <ul>
          <li class="fbxx_footer_zi4">商机类型：</li>

          <% Shangjidingzhi.get_info_type_values.each do |shangjidingzhis| %>
            <li class="dxanniu2">
            <%= f.radio_button :info_type, shangjidingzhis[1] %>
            </li>
            <li class="fbxx_footer_zi2"><%= shangjidingzhis[0] %></li>
          <% end %>
        </ul>
        <ul>
          <li class="fbxx_footer_zi4">提醒方式：</li>
          <li>
          <%= f.input :is_send_email, input_html: {class: "dxanniu2"}, label: false, wrapper: false %>
          </li>
          <li class="fbxx_footer_zi2"> 发送电子邮件通知我 </li>
        </ul>
        <ul>
          <li class="fbxx_footer_zi4">您的Email：</li>
          <li>
          <%= f.input :email, as: :string, disabled: true, input_html: {value: current_user.valid_email, class: "wenben7"}, label: false, wrapper: false %>
          </li>
        </ul>
        <ul>
          <li>
          <%= f.button :submit, "确认定制", class: "anniu12", style: "background:url(/assets/fbxx_anniu.gif)" %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="clear"></div>
</div>

app/views/shangjidingzhis/edit.html.erb
<% title "编辑商机" %>

<%= render 'form' %>

app/views/shangjidingzhis/index.html.erb
<% title "商机定制管理" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">商机定制管理</div>
  <% if @shangjidingzhis.size > 0 %>
    <div class="sjdz_bt">
      <span class="xjgl">供求商机管理</span>
      <span class="xjgl_2">
        <%= link_to "订阅新的商机", new_shangjidingzhi_path, target: "_blank" %>
      </span>
    </div>
    <div class="sjdz_xia">
      <div class="sjdz_xia_top">
        <ul>
          <li class="sjdz_xia_zi1"><strong>订阅内容</strong></li>
          <li class="sjdz_xia_zi2"><strong>商机类型</strong></li>
          <li class="sjdz_xia_zi3"><strong>地区</strong></li>
          <li class="sjdz_xia_zi3"><strong>提醒方式</strong></li>
          <li class="sjdz_xia_zi3"><strong>操作</strong></li>
        </ul>
      </div>

      <div class="sjdz_xia_bot">
        <% @shangjidingzhis.each do |shangjidingzhi| %>
          <ul>
            <li class="sjdz_xia_zi1">
            <%= link_to shangjidingzhi.keyword, list_shangjidingzhis_path(id: shangjidingzhi), title: shangjidingzhi.keyword %>
            </li>
            <li class="sjdz_xia_zi2">
            <%= shangjidingzhi.info_type_text %>
            </li>
            <li class="sjdz_xia_zi3">
            <%= shangjidingzhi.address %>
            </li>
            <li class="sjdz_xia_zi3">
            <%= shangjidingzhi.is_send_email_text %>
            </li>
            <li class="sjdz_xia_zi3">
            <%= link_to '编辑', edit_shangjidingzhi_path(shangjidingzhi) %>| 
            <%= link_to '删除', shangjidingzhi, confirm: '确定删除吗?', method: :delete %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="sjdz_tixing1">邮件地址提醒</div>
    <div class="sjdz_tixing2">
      当前用于接收的电子邮箱为：<%= current_user.valid_email %>  
      <a href="<%= edit_user_registration_path %>">
        <font color="#999999">修改</font>
      </a>
    </div>
    <%= will_paginate @shangjidingzhis %>
  <% else %>
    <div class="dingyue1">
      <ul>
        <li><%= current_user.call %>， 您好！ </li>
        <li> 以下是您订阅的最新商机，快去看看有没有合适的客户吧！ </li>
      </ul>
    </div>
    <div class="dingyue2">
      您还没有订阅在线商机信息，<img src="/assets/tb23.gif" />
      <%= link_to "点此订阅", new_shangjidingzhi_path, target: "_blank" %>
    </div>

  <% end %>
</div>
<div class="clear"></div>


<script text="type/javascript">
  $(function(){
    $("#shangjiguanli").addClass("ht_dianji2")
  })
</script>

app/views/shangjidingzhis/list.html.erb
<% title "最新在线商机" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">最新在线商机</div>
  <% if @shangjidingzhis.size > 0 %>
    <div class="sdly_k3"><%= current_user.call %> ， 您好！<br/>
      以下是您订阅的最新商机，快去看看有没有合适的客户吧！</div>
    <div class="zxsj_xia">
      <% @shangjidingzhis.each do |shangji| %>
        <div class="zxsj_bt">
          <%= link_to shangji.keyword, list_shangjidingzhis_path(id: shangji) %>
        </div>
      <% end %>

      <div class="zxsj_bot">
        <% @transactions.each do |t| %>
          <ul>
            <div class="gqxx_left_nrbot_pic">
              <a href="<%= transaction_path(t) %>">
                <%= head_image t, width: 110, height: 95 %>
              </a>
            </div>
            <li class="zxsj_bot_zik">
            <span class="zxsj_bot_zi1">
              <%= link_to truncate(t.title, length: 18), transaction_path(t), title: t.title %>
            </span>
            <span class="zxsj_bot_zi2">
              <font color="#006699"><%= t.info_type_text %></font> 
              <%= l t.refreshed_at.to_date %>
            </span>
            <span class="zxsj_bot_zi3"><%= truncate t.desc, length: 70 %></span>
            </li>
            <li class="zxsj_bot_zi4"><%= t.user.member_text %></li>
            <li class="zxsj_bot_lxk">
            <span class="zxsj_bot_zi5">
              <%= link_to truncate(t.user.company_name, length: 20), website_path(t.user), title: t.user.company_name %>
            </span>
            <span class="zxsj_bot_zi6">
              <%= link_to "留言", website_path(t.user, category: "message") %>
            </span>
            <span class="zxsj_bot_zi7">
              <%= link_to "联系方式", website_path(t.user, category: "contact") %>
            </span> 
            </li>
          </ul>
        <% end %>
      </div>
    </div>
    <%= will_paginate @transactions %>
  <% else %>
    <div class="dingyue1">
      <ul>
        <li><%= current_user.call %>您好 ， 您好！ </li>
        <li> 以下是您订阅的最新商机，快去看看有没有合适的客户吧！ </li>
      </ul>
    </div>
    <div class="dingyue2">
      您还没有订阅在线商机信息，<img src="/assets/tb23.gif" />
      <%= link_to "点此订阅", new_shangjidingzhi_path, target: "_blank" %>
    </div>
  <% end %>
</div>
<div class="clear"></div>



<script text="type/javascript">
  $(function(){
    $("#new_shangji").addClass("ht_dianji2")
  })
</script>

app/views/shangjidingzhis/new.html.erb
<% title "订阅新的商机" %>

<%= render 'form' %>