config/routes.rb
Resources::Application.routes.draw do

  resources :hangqingbaojias, only: [:index] do
    collection do 
      get "jiage_list"
      get "more_jiage_list"
      get "hangqing_list"
      get "dongtai_list"
      get "more_dongtai_list"
      get "comment"
    end
  end

  resources :jiages do 
    collection do 
      get "get_categories"
    end
  end

  resources :dongtais

  resources :hangqings

  resources :comments do
    collection do 
      get "list"
    end
  end

  resources :contacts

  resources :message_types

  resources :lanzis, only: [:index, :create, :destroy]

  resources :customer_types

  resources :customers

  resources :news

  resources :transaction_types

  resources :shangjidingzhis do 
    collection do
      get "list"
    end
  end

  resources :company_prices
  resources :jiaoyis, only: [:index, :show]
  resources :baojias, only: [:index]
  resources :hangqingbaojias, only: [:index]
  resources :zixuns, only: [:index] do 
    collection do
      get "list"
    end
  end

  get "home" => "home#index"
  get "shangbiao" => "home#shangbiao"
  get "shengming" => "home#shengming"
  get "services" => "home#services"
  get "privacy" => "home#privacy"
  get "ad" => "home#ad"
  get "lianxi" => "home#lianxi"
  get "recruit" => "home#recruit"
  get "guanggao_attachment" => "home#guanggao_attachment"
  get "search_home" => "home#search"
  get "search_by_tag_home" => "home#search_by_tag"
  get "admin" => "admin#index"

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_scope :user do
    get "bianji_mima", :to => "devise/registrations#bianji_mima"
    put "update_password", :to => "devise/registrations#update_password"
  end

  resources :regions, only: [:show]

  resources :countries, only: [:show]

  get 'verify_email_exist' => "users#verify_email_exist"
  get 'verify_username_exist' => "users#verify_username_exist"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get "entverify"
      put "verify"
      get "purview"
      get "entmember"
      put "member"
      get "home"
      get "info_and_image"
      get "edit_desc"
      put "update_desc"
      get "edit_image"
      get "edit_license"
    end
  end

  resources :transactions do
    member do
      get "images"
    end

    collection do
      get "tags"
      get "refresh"
    end

    member do
      get "change_transaction_type"
    end
  end

  delete "delete_transactions" => "transactions#destroy"

  resources :links

  resources :attachments do
    collection do
      post "upload"
    end
  end

  resources :categories, only: :show
  resources :company_price_categories, only: :show
  resources :articles
  resources :messages do
    collection do
      put "restore"
    end
  end

  constraints(Subdomain) do
    match '/' => 'member#home', as: "member_home"
    match '/member/show' => 'member#show'
    match '/member/contact' => 'member#contact'
    match '/member/transactions' => 'member#transactions'
    match '/member/transaction/:id' => 'member#transaction', as: "member_transaction"
    match '/member/news' => 'member#news'
    match '/member/message' => 'member#message'
    match '/member/news/:id' => 'member#new', as: "member_new"
  end

  root to: "home#index"

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:error).call(env) }  # 因为application.rb捕获不到rails路由错误，所以rails路由报错后指向application_controller.rb中的error action.

end

app/models/jiage.rb
# coding: utf-8

class Jiage < Hangqingbaojia

  extend ActiveHash::Associations::ActiveRecordExtensions

  validates_presence_of :title, :resource_id, :category_id, :published_at

  belongs_to_active_hash :resource, class_name: "KeyValues::Resource"
  belongs_to_active_hash :category, class_name: "KeyValues::PriceCategory"

  scope :jinshu, where(resource_id: 1)
  scope :suliao, where(resource_id: 2)
  scope :zhi, where(resource_id: 3)
  scope :xiangjiao, where(resource_id: 4)

  def pre?
    id != self.class.first.id
  end

  def next?
    id != self.class.last.id
  end

  def pre
    self.class.where("id < ?", id).order("id DESC").limit(1).last
  end

  def next
    self.class.where("id > ?", id).limit(1).first
  end


end

app/controllers/jiages_controller.rb
# coding: utf-8

class JiagesController < ApplicationController

  load_resource except: :get_categories 
  authorize_resource except: :show

  before_filter :filter_tag_list, only: [:create, :update]
  before_filter :authenticate_user!, except: :show
  layout "admin", only: [:index, :new, :edit, :create, :update]

  def index
    @search = Jiage.search(params[:search])
    @jiages = @search.order("created_at DESC").page(params[:page]).per_page(22)
  end

  # GET /jiages/1
  # GET /jiages/1.json
  def show
    @jiage = Jiage.find(params[:id])
    @jiages = @jiage.resource.jiages.limit(12).order("published_at DESC")
  end

  # GET /jiages/new
  # GET /jiages/new.json
  def new
    @jiage = KeyValues::Resource.first.jiages.new(published_at: Date.current)
  end

  # GET /jiages/1/edit
  def edit
    @jiage = Jiage.find(params[:id])
  end

  # POST /jiages
  # POST /jiages.json
  def create
    @jiage = Jiage.new(params[:jiage])

    if @jiage.save
      redirect_to jiages_path, notice: '创建成功'
    else
      format.html { render action: "new" }
    end
  end

  # PUT /jiages/1
  # PUT /jiages/1.json
  def update
    @jiage = Jiage.find(params[:id])

    if @jiage.update_attributes(params[:jiage])
      redirect_to jiages_path, notice: '价格更新成功'
    else
      render action: "edit"
    end
  end

  # DELETE /jiages/1
  # DELETE /jiages/1.json
  def destroy
    @jiage = Jiage.find(params[:id])
    @jiage.destroy

    redirect_to jiages_url
  end

  def get_categories
    resource = KeyValues::Resource.find(params[:id])
    render json: resource.price_categories.collect{|category| {id: category.id, name: category.name}}
  end

  private

  def filter_tag_list
    params[:jiage][:tag_list] = params[:jiage][:tag_list].values.join(",")
  end

end

app/helpers/jiages_helper.rb
module JiagesHelper
end

app/views/jiages/_form.html.erb
<div class="gly_fbwz_xia">
  <%= simple_form_for(@jiage, html: {class: "validate_form"}) do |f| %>
  <ul>
    <li class="gly_fbwz_zi1"><span class="require">*</span>标题：</li>
    <%= f.input :title, input_html: {class: "validate[required] wenben7"}, label: false, wrapper: false %>
  </ul>
  <ul>
    <li class="gly_fbwz_zi1"><span class="require">*</span>资源分类：</li>
    <%= f.input :resource_id, collection: KeyValues::Resource.all, include_blank: "请选择资源分类", input_html: {class: "validate[required] wenben7"}, label: false, wrapper: false %>
  </ul>
  <ul>
    <li class="gly_fbwz_zi1"><span class="require">*</span>二级分类：</li>
    <%= f.input :category_id, collection: @jiage.resource.price_categories, include_blank: "请选择二级分类", input_html: {class: "validate[required] wenben7"}, label: false, wrapper: false %>
  </ul>

  <ul>
    <li class="gly_fbwz_zi1"><span class="require">*</span>发布日期：</li>
    <%= f.input :published_at, as: :string, input_html: {class: "validate[required] wenben7 date"}, label: false, wrapper: false %>
  </ul>
  <ul>
    <li class="gly_fbwz_zi1">标签：</li>
    <% 0.upto(4) do |i| %>
      <li>
      <%= text_field_tag "jiage[tag_list][#{i}]", @jiage.tag_list[i], class: "wenben12" %>
      </li>
    <% end %>
  </ul>
  <ul>
    <li class="gly_fbwz_zi2">内容：</li>
    <li class="gly_fbwz_bianjiqi">
      <%= f.input :desc, input_html: {class: "kindeditor"}, label: false, wrapper: false %>
    </li>
  </ul>

  <ul>
    <%= f.button :submit, class: "anniu8" %>
  </ul>
<% end %>
</div>


<script>

$(function(){
  $("#jiage_resource_id").change(function(){
    var resource_id = $(this).attr("value")
    $.get("<%= get_categories_jiages_path %>", {id: resource_id}, function(data){
      $("#jiage_category_id").html("")
      $("#jiage_category_id").append("<option value=''>请选择二级分类</option>")
      $.each(data, function(key, value){
        $("#jiage_category_id").append("<option value='+" + value.id + "'>" + value.name + "</option>")
      })
    })
  })
})
</script>

app/views/jiages/_right.html.erb
  <div class="fl2_bottom_right">
    <div class="fl1_right_k1">
      <div class="box1_right_xia_top"><span class="box1_right_xia_topzi1"><strong>各地<%= resource.name %>价格查询</strong></span></div>
      <div class="fl1_right_k1_xia">
      <ul>
        <% resource.hangqingbaojias.top_tags(12).each do |tag| %>
          <li><%= link_to truncate(tag.name, length: 5), search_home_path(category: "hangqing", keyword: tag.name), target: "_blank", title: tag.name %></li>
        <% end %>
      </ul>
      </div>
    </div>
    <div class="guanggao1">
      <%= image_tag "gg1.gif" %>
    </div>
    <% if resource.id != 3 %>
    <div class="box3_right_1k">
      <div class="box1_right_xia_top"><span class="box1_right_xia_topzi1"><strong><%= resource.name %>行情导读</strong></span></div>
      <div class="box3_right_1k_xia">
        <ul>
          <% resource.hangqings.limit(8).order("published_at DESC").each do |hangqing| %>
            <li>·<%= link_to truncate(hangqing.title, length: 18), hangqing, title: hangqing.title, target: "_blank" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="guanggao1">
      <%= image_tag "gg1.gif" %>
    </div>
  <% end %>
  <% if resource.id != 4 %>
    <div class="box3_right_1k">
      <div class="box1_right_xia_top"><span class="box1_right_xia_topzi1"><strong><%= resource.name %>最新市场动态</strong></span></div>
      <div class="box3_right_1k_xia">
        <ul>
        <% resource.dongtais.order("published_at DESC").limit(8).each do |dongtai| %>
            <li>·<%= link_to truncate(dongtai.title, length: 18), dongtai, title: dongtai.title, target: "_blank" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="guanggao1">
      <%= image_tag "gg1.gif" %>
    </div>
  <% end %>
  </div>

app/views/jiages/edit.html.erb
<% title "编辑行情价格" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">编辑行情价格</div>
  <%= render 'form' %>
</div>
<div class="clear"></div>

app/views/jiages/index.html.erb
<% title "行情价格列表" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">行情价格列表</div>
  <div class="gly_lb_xia">
    <div class="gly_lb_xia_top">
      <ul>
        <li class="gly_lb_xia_top_zi1_my">
        <strong>
          <%= sort_link @search, :title, category: params[:category] %>
        </strong>
        </li>
        <li class="gly_lb_xia_top_zi3">
        <strong>
          <%= sort_link @search, :published_at, category: params[:category] %>
        </strong>
        </li>
        <li class="gly_lb_xia_top_zi4"><strong>操作</strong></li>
      </ul>
    </div>
    <div class="gly_lb_xia_bot">
      <% @jiages.each do |jiage| %>
        <ul>
          <span class="fuxuank"><input name="" type="checkbox" value="" /></span>
          <li class="gly_lb_xia_top_zi1_my"><%= link_to truncate(jiage.title, length: 35), jiage, title: jiage.title, target: "_blank" %></li> 
          <li class="gly_lb_xia_top_zi3"><%= (l jiage.published_at) if jiage.published_at %></li>
          <li class="gly_lb_xia_top_zi4">
          <%= link_to '编辑', edit_jiage_path(jiage) %> | 
          <%= link_to '删除', jiage, confirm: '确定删除吗?', method: :delete %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
  <%= will_paginate @jiages %>
</div>
<div class="clear"></div>
</div>

app/views/jiages/new.html.erb
<% title "发布行情价格" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">发布行情价格</div>
  <%= render 'form' %>
</div>
<div class="clear"></div>

app/views/jiages/show.html.erb
<div class="weizhi">
  当前位置：<%= link_to '首页', home_path %> > <%= link_to "行情报价", hangqingbaojias_path %>  > <font color="#FF6600"><%= @jiage.title %></font>
</div>
<div class="fl2_bottom">
  <div class="fl2_bottom_left">
    <div class="fl2_left_k">
      <div class="nry_left_k_zi1"><%= @jiage.title %></div>
      <div class="nry_left_k_zi2">
        发表时间：<%= @jiage.published_at %> 
        相关标签：
        <% @jiage.tag_list.each do |tag| %>
          <%= link_to tag, search_home_path(category: "hangqing", keyword: tag), target: "_blank" %>
        <% end %>
      </div>
      <div class="nry_left_text"><%= @jiage.desc.html_safe %></div>
      <span class="fl2_left_biaoqian">
        标签：
        <% @jiage.tag_list.each do |tag| %>
          <%= link_to tag, search_home_path(category: "hangqing", keyword: tag), target: "_blank" %>
        <% end %>
      </span>
      <div class="nry_left_k_botk">
        <span class="nry_left_k_zi6">
        <% if @jiage.pre? %>
          上一篇：<%= link_to truncate(@jiage.pre.title, length: 20), @jiage.pre, title: @jiage.pre.title %>
        <% end %>
        </span>
        <span class="nry_left_k_zi6">
        <% if @jiage.next? %>
          下一篇：<%= link_to truncate(@jiage.next.title, length: 20), @jiage.next, title: @jiage.next.title %>
        <% end %>
        </span>
      </div>
    </div>
    <div class="fl2_left_k2">
      <div class="lby_left_top"><%= @jiage.resource.name %>最新报价</div>
      <div class="fl2_left_xiak">
      <ul>
        <% @jiages.each_with_index do |jiage, index| %>
          <% if index % 2 == 0; n = 2; else n = 1; end%>
            <li class="fl2_left_xiak_zi<%= n %>">
            ·<%= link_to truncate(jiage.title, length: 20), jiage, title: jiage.title, target: "_blank" %>
          <font color="#999999"><%= jiage.published_at %></font>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
  <%= render partial: "right", locals: {resource: @jiage.resource} %>
<div class="clear"></div>
</div>