config/routes.rb
Resources::Application.routes.draw do

  resources :hangqingbaojias, only: [:index] do
    collection do 
      get "jiage_list"
      get "more_jiage_list"
      get "hangqing_list"
      get "dongtai_list"
      get "more_dongtai_list"
      get "comment"
    end
  end

  resources :jiages do 
    collection do 
      get "get_categories"
    end
  end

  resources :dongtais

  resources :hangqings

  resources :comments do
    collection do 
      get "list"
    end
  end

  resources :contacts

  resources :message_types

  resources :lanzis, only: [:index, :create, :destroy]

  resources :customer_types

  resources :customers

  resources :news

  resources :transaction_types

  resources :shangjidingzhis do 
    collection do
      get "list"
    end
  end

  resources :company_prices
  resources :jiaoyis, only: [:index, :show]
  resources :baojias, only: [:index]
  resources :hangqingbaojias, only: [:index]
  resources :zixuns, only: [:index] do 
    collection do
      get "list"
    end
  end

  get "home" => "home#index"
  get "shangbiao" => "home#shangbiao"
  get "shengming" => "home#shengming"
  get "services" => "home#services"
  get "privacy" => "home#privacy"
  get "ad" => "home#ad"
  get "lianxi" => "home#lianxi"
  get "recruit" => "home#recruit"
  get "guanggao_attachment" => "home#guanggao_attachment"
  get "search_home" => "home#search"
  get "search_by_tag_home" => "home#search_by_tag"
  get "admin" => "admin#index"

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_scope :user do
    get "bianji_mima", :to => "devise/registrations#bianji_mima"
    put "update_password", :to => "devise/registrations#update_password"
  end

  resources :regions, only: [:show]

  resources :countries, only: [:show]

  get 'verify_email_exist' => "users#verify_email_exist"
  get 'verify_username_exist' => "users#verify_username_exist"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get "entverify"
      put "verify"
      get "purview"
      get "entmember"
      put "member"
      get "home"
      get "info_and_image"
      get "edit_desc"
      put "update_desc"
      get "edit_image"
      get "edit_license"
    end
  end

  resources :transactions do
    member do
      get "images"
    end

    collection do
      get "tags"
      get "refresh"
    end

    member do
      get "change_transaction_type"
    end
  end

  delete "delete_transactions" => "transactions#destroy"

  resources :links

  resources :attachments do
    collection do
      post "upload"
    end
  end

  resources :categories, only: :show
  resources :company_price_categories, only: :show
  resources :articles
  resources :messages do
    collection do
      put "restore"
    end
  end

  constraints(Subdomain) do
    match '/' => 'member#home', as: "member_home"
    match '/member/show' => 'member#show'
    match '/member/contact' => 'member#contact'
    match '/member/transactions' => 'member#transactions'
    match '/member/transaction/:id' => 'member#transaction', as: "member_transaction"
    match '/member/news' => 'member#news'
    match '/member/message' => 'member#message'
    match '/member/news/:id' => 'member#new', as: "member_new"
  end

  root to: "home#index"

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:error).call(env) }  # 因为application.rb捕获不到rails路由错误，所以rails路由报错后指向application_controller.rb中的error action.

end

app/controllers/home_controller.rb
# coding: utf-8 

class HomeController < ApplicationController
  def index
    @search = Transaction.search(params[:search])
    @transactions = @search.page(params[:page]).per_page(50).order("created_at DESC")
    @company_prices = CompanyPrice.order("created_at DESC").limit(9)
    @supply_infos = Transaction.supply.limit(6).order("created_at DESC")
    @seeking_infos = Transaction.seeking.limit(6).order("created_at DESC")
    @articles = Article.common.order("created_at DESC").limit(8)
    @article = Article.important.last
    @users = User.where({admin: false}).order("created_at DESC").limit(6)
    @tuijian_transactions = Transaction.order("created_at DESC").limit(6)
    @hangye_articles = Article.hangye.common.order("created_at DESC").limit(6)
    @zhengce_articles = Article.zhengce.common.order("created_at DESC").limit(6)
    @zaisheng_articles = Article.zaisheng.common.order("created_at DESC").limit(6)
    @zhishi_articles = Article.zhishi.common.order("created_at DESC").limit(6)
    @hangye_article = Article.hangye.less_important.last
    @zhengce_article = Article.zhengce.less_important.last
    @zaisheng_article = Article.zaisheng.less_important.last
    @zhishi_article = Article.zhishi.less_important.last
    @jiages_jinshu = Jiage.jinshu.order("published_at DESC").limit(8)
    @jiages_suliao = Jiage.suliao.order("published_at DESC").limit(8)
    @jiages_zhi = Jiage.zhi.order("published_at DESC").limit(8)
    @jiages_xiangjiao = Jiage.xiangjiao.order("published_at DESC").limit(8)

  end

  def search
    @category, @keyword, @refreshed_at = params["category"], params["keyword"], params[:refreshed_at]
    shijian = case @refreshed_at
              when "1" then 1.days
              when "3" then 3.days
              when "7" then 7.days
              when "30" then 1.month
              when "60" then 2.months
              end
    refreshed_at = shijian ? Time.now - shijian : nil
    if @category == "supply" || @category == "seeking" || @category.nil?
      @search = Transaction.search(params[:search].try(:merge, {refreshed_at_gte: refreshed_at})).relation.search_by_category(@category, @keyword)
      @transactions = @search.paginate(page: params[:page], per_page: 15)
      @company_prices = CompanyPrice.search({name_like: @keyword}).order("created_at DESC").limit(8)
      render "search_transactions"
    elsif @category == "price"
      @search = CompanyPrice.search({name_like: @keyword})
      @company_prices = @search.page(params[:page]).per_page(20).order("created_at DESC")
      render "search_company_prices"
    else 
      @search = Hangqingbaojia.search_by_title_or_tag(@keyword)
      @hangqings = @search.paginate(page: params[:page], per_page: 36)
      render "search_hangqingbaojias"
    end
    
  end

  def search_by_tag
    @tag = params[:tag]
    @transactions = Transaction.tagged_with(params[:tag]).page(params[:page]).per_page(10).order("created_at DESC")
    @company_prices = CompanyPrice.order("created_at DESC").limit(8)
    @tags = Transaction.search_by_title_and_category(@tag).top_tags(30)
    @articles = Article.order("created_at DESC").limit(8)
  end

  def shangbiao
  end

  def shengming
  end

  def services
  end

  def privacy
  end

  def ad
  end

  def lianxi
  end

  def recruit
  end

  def guanggao_attachment
    user_agent = request.user_agent.downcase
    file_name = user_agent.include?("msie") ? CGI::escape("资源再生交易平台商业推广书-广告.doc") : "资源再生交易平台商业推广书-广告.doc"
    send_file File.join(Rails.root, "public", "attachments", "guanggao_attachment.doc"), :type => "application/xlsx;charset=utf-8", :filename => file_name
  end

end

app/helpers/home_helper.rb
# coding: utf-8 

module HomeHelper
end

app/views/home/ad.html.erb
<div class="zhuzuok">
广告投放<br/>
本网站相关广告投放欢迎联系客服+86-010-68392872。或发送邮件至Postmaster@crra010.com。<br/>
我们衷心期待与您进行更加密切深入的合作与发展。<br/>
广告投放，详情请下载<%= link_to '附件', guanggao_attachment_path %>。<br/>
</div>

app/views/home/lianxi.html.erb
<div class="zhuzuok">
<ul><li class="neirong2"><strong><font color="#FF6600">客户服务</font></strong></li>
<li class="neirong2">资源再生交易平台</li>
<li class="neirong2">请<font color="#FF6600">致电+86-010-68392872或发送邮件至postmaster@crra010.com</font>给客户服务部留言（热线开放时间：北京时间星期一至五上午9:30至下午17:30）</li>
</ul>
<div class="clear"></div>
</div>

app/views/home/recruit.html.erb
<div class="zhuzuok">
<strong>资源再生交易平台，是由国家认证授权的首家再循环经济在线交易平台。</strong><br/>
在国家“十二五”经济规划的大背景中，全面发展再循环经济、扶持再生资源行业成为我国未来经济计划中的重要任务，依托重大专项建立产业化平台、支持关键技术、装备和产品研发与相关服务业支撑技术研究等多项措施，加强战略性新兴再生资源产业的科技支撑。大力开展资源再生先进技术、装备和产品的研发和推广，引导和培育战略性新兴再生资源产业的健康发展。循环经济正处于蓬勃兴起的阶段。<br/>
在认识到国家的相关政策与行业的未来规划后，经过中国物资协会领导的指示与公司内部的谨慎研究，我们对网站进行了全面改版升级，我们的服务对象扩展到再生资源方面的全部产品类别，在自我完善的同时亦扩大了市场覆盖面，服务于更多的资源回收行业商家。<br/>
同时我们仍旧注重于报废汽车零部件的在线交易功能，并将以前的报废汽车零部件平台单设为新平台下属的一个频道。<br/>
我们以自身的技术优势，依靠各部委与行业协会的大力支持，以为企业服务，为政府与行业协会服务，为再循环经济服务为宗旨。在给各会员企业带来可见的经济效益的同时，也为各主管部委和行业协会上报真实可信的相关行业数据及企业建议。并在各企业之间、在各企业与主管部委及行业协会之间，建立起长期、有效、快捷的沟通桥梁。使再生行业中的各类信息能够快速、有序、有效地进行互动。<br/>

</div>

app/views/home/search_by_tag.html.erb
<% title "#{@transactions.total_entries.size}" %>

<div class="lby_bottom">
  <div class="lby_bottom_left">
    <div class="xxlb_left_bq">
      <ul>
        <li class="xxlb_left_bq_zi1">
        <strong>标签：</strong><%= @tag %>的信息列表:
        </li>
        <li class="xxlb_left_bq_zi2">
        供求信息<%= @transactions.total_entries %>条
        </li>
      </ul>
    </div>
    <div class="xxlb_left_btk">
      <ul>
        <li class="xxlb_left_btk_zi1"><%= @tag %>供求信息</li>
        <li class="xxlb_left_btk_zi2"> 
        <%= link_to "查看所有#{@tag}交易信息", search_home_path(keyword: @tag) %>
        </li>
      </ul>
    </div>
    <div class="lby_left_xia">
      <div class="lby_left_xia_bot">
        <% @transactions.each do |t| %>
          <ul>
            <div class="xxlb_zik1">
              <li class="xxlb_left_nrzi1">
              <%= link_to truncate(t.name, length: 28), t, title: t.name %>
              </li>
              <li class="xxlb_left_nrzi2">
              <%= link_to t.user.company_name, website_path(t.user), title: t.user.company_name %>
              </li>
            </div>
            <li class="lby_left_xia_zi2">
            <%= l t.created_at.to_date %>
            </li>
            <li class="xxlb_left_nrzi3"> 
            <%= t.info_type_text %>： <%= truncate t.desc, length: 50 %>
            </li>
          </ul>
        <% end %>
        <%= will_paginate @transactions %>

        <div class="clear"></div>
      </div>
    </div>

  </div>
  <div class="lby_bottom_right">
    <div class="box3_right_1k">
      <div class="box1_right_xia_top">
        <span class="box1_right_xia_topzi1">
          <strong>最新产品报价</strong>
        </span>
      </div>
      <div class="box3_right_1k_xia">
        <ul>
          <% @company_prices.each do |price| %>
            <li>
            ·<%= link_to truncate("#{price.name} #{price.price}", length: 18), price, title: "#{price.name} #{price.price}" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="xxlb_right_k1">
      <div class="box1_right_xia_top">
        <span class="box1_right_xia_topzi1">
          <strong>搜索标签</strong>
        </span>
      </div>
      <div class="xxlb_right_k2">
        <%= form_tag search_by_tag_home_path, method: "get" do %>
          <%= text_field_tag "tag", params[:tag], class: "wenben14" %>
          <%= submit_tag "搜索", class: "xxlb_button" %>
        <% end %>
      </div>
    </div>
    <div class="gqxx_right_k1">
      <div class="jyzx_header_right_bt">
        <span class="box1_right_xia_topzi1">
          <strong><%= @tag %>相关标签</strong>
        </span>
      </div>
      <div class="gqxx_right_k1_xia">
        <ul>
          <% @tags.each do |tag| %>
            <li class="<%= ["yellow", "black", "red", "black", "green", "blue"][rand(6)] %>">
            <%= link_to tag.name, search_by_tag_home_path(tag: tag.name) %>
            </li>
            <li>|</li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="box3_right_1k">
      <div class="box1_right_xia_top">
        <span class="box1_right_xia_topzi1">
          <strong>热点资讯</strong>
        </span>
      </div>
      <div class="box3_right_1k_xia">
        <ul>
          <% @articles.each do |article| %>
            <li>
            ·<%= link_to truncate(article.title, length: 16), article, title: article.title %>
            </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="clear"></div>

app/views/home/search_hangqingbaojias.html.erb
<div class="weizhi">
  当前位置：<%= link_to "首页", home_path %> > <%= link_to "行情报价", hangqingbaojias_path %> > <font color="#FF6600">行情报价信息搜索</font>
</div>
<div class="fl1_bottom">
  <div class="fl1_bottom_left">
    <div class="fl5_k">
      <div class="fl5_btzi1">您搜索的报价关键字为：<font color="#FF0000"><%= @keyword %></font></div>
      <div class="fl5_btzi2">
        精确报价，买卖商机，尽在crra010再生交易平台
      </div>
    </div>
    <div class="fl5_left_xiak">
      <ul>
        <% @hangqings.each_with_index do |hangqing, index| %>
          <li class="fl5_left_xiak_text">
          <%= link_to hangqing.title, hangqing, target: "_blank" %>
          <font color="#999999">
            <%= hangqing.published_at %>
          </font>
          </li>
          <% if index > 0 && index % 5 == 0 %>
            <div class="xuxian"></div>
          <% end %>
        <% end %>
      </ul>
      <%= will_paginate @hangqings %>
    </div>
  </div>
  <%= render partial: "/hangqingbaojias/right", locals: {resource: KeyValues::Resource.first} %>
  <div class="clear"></div>
</div>

app/views/home/search_transactions.html.erb
<% title "供求信息" %>

<% if true %>
  

  <div class="weizhi">当前位置：<%= link_to "首页", home_path %> > <%= link_to "交易中心", jiaoyis_path %>  > <font color="#FF6600">供求信息</font></div>
  <div class="gqxx_bottom">
    <div class="gqxx_bottom_left">
        <div class="xiangguan_ser">
        <ul>
          <li><font color="#000000">相关搜索：</font></li>
          <% Category.roots.each do |category| %>
            <li><%= link_to category.name, search_home_path(keyword: category.name) %></li>
          <% end %>
        </ul>
      </div>
      <div class="gy_text">共有<font color="#FF0000"><%= @transactions.total_entries %></font>条关于<font color="#006699"><strong><%= @keyword %></strong></font>的信息</div>
      <div class="gqxx_left_xia">
        <div class="bar">
          <% [["全部信息", nil], ["供应信息", "supply"], ["求购信息", "seeking"]].each_with_index do |info, index| %>
            <div id="newB<%= index.succ %>">
              <%= link_to info[0], search_home_path(category: info[1], keyword: @keyword, region_id: @region_id, refreshed_at: @refreshed_at) %>
            </div>
          <% end %> 
        </div>

        <div class="bar_xia">
          <div id="newA1">
            <div class="gqxx_left_search2">
              <%= form_tag search_home_path, method: "get" do %>
                <div class="gqxx_left_search2_text">精确搜索：</div>
                <%= select_tag "search[user_region_id_eq]", options_for_select(Region.all.map{|r| [r.name, r.id]}, @region_id), prompt: "请选择一个省份", class: "xialacaidan6" %>
                <%= select_tag "refreshed_at", options_for_select([["1天内", 1], ["3天内", 3], ["一周内", 7], ["一个月内", 30], ["两个月内", 60]], @refreshed_at), prompt: "请选择发布时间", class: "xialacaidan6" %>

                <div class="gqxx_left_search2_text">关键字：</div>
                <%= text_field_tag "keyword", @keyword, class: "wenben6" %>
                <%= submit_tag "筛选", class: "anniu7", style: "background:url(/assets/anniu5.gif)" %>
              <% end %>
            </div>
            <div class="gqxx_left_btk">
              <ul>
                <li class="gqxx_left_btzi1">产品图片</li>
                <li class="gqxx_left_btzi2">产品信息</li>
                <li class="gqxx_left_btzi3">所属地区</li>
                <li class="gqxx_left_btzi3">价格</li>
                <li class="gqxx_left_btzi4">联系方式</li>
              </ul>
            </div>

            <div class="gqxx_left_nrbot_dak">
              <div class="gqxx_left_nrbot">
                <% @transactions.each do |t| %>
                <ul>
                  <span class="gqxx_left_nrbot_pic">
                    <%= link_to (head_image t, width: 110, height: 95), t, target: "_blank" %>
                  </span>
                  <li class="gqxx_left_nrbot_zik">
                  <span class="gqxx_left_nrbot_zi1">
                    <%= link_to truncate(t.title, length: 13), t, target: "_blank" %>
                  </span>
                  <span class="gqxx_left_nrbot_zi2">
                    <%= l t.refreshed_at.to_date %>
                  </span>
                  <span class="gqxx_left_nrbot_zi3">
                    <%= t.info_type_text %>：<%= truncate t.desc, length: 55 %>
                  </span>
                  <span class="gqxx_left_nrbot_zi4">
                    <%= link_to truncate(t.user.company_name, length: 35), website_path(t.user), target: "_blank" %>
                  </span>          
                  </li>
                  <li class="gqxx_left_btzi5">
                    <%= t.user.suozaidi %>
                  </li>
                  <li class="gqxx_left_btzi5">
                    <%= t.price_by_unit %>
                  </li>
                  <li class="gqxx_left_lxfsk">
                  <span class="gqxx_left_btzi6">
                    <%= link_to "给我留言", website_path(t.user, category: "message"), target: "_blank" %>
                  </span>
                  <span class="gqxx_left_btzi7">
                    <%= link_to "联系方式", website_path(t.user, category: "contact"), target: "_blank" %>
                  </span>          
                  </li>
                </ul>
                <% end %>
                </div>
                <%= will_paginate @transactions %>
              </div>
            </div>

            <div class="gqxx_left_di_anniu">
              <%= link_to "发布供应信息", new_transaction_path(info_type: "supply") %>
            </div>
            <div class="gqxx_left_di_anniu2">
              <%= link_to "发布求购信息", new_transaction_path(info_type: "seeking") %>
            </div>
            <div class="gqxx_left_di_zi">还没有找到合适的客户？发布您供求信息，让客户主动找上门！</div>
            <div class="clear"></div>
          </div>
        </div>
      </div>
      <div class="gqxx_bottom_right">
        <div class="guanggao1"><img src="/assets/gg1.gif" /></div>
        <div class="gqxx_right_k1">
          <div class="jyzx_header_right_bt">
            <span class="box1_right_xia_topzi1">
              <strong><%= @keyword %>相关标签</strong>
            </span>
          </div>
          <div class="gqxx_right_k1_xia">
            <ul>
              <% Transaction.search_by_title_and_category(@keyword).top_tags(30).each do |tag| %>
                <li class="<%= ["yellow", "black", "red", "black", "green", "blue"][rand(6)] %>">
                <%= link_to tag.name, search_by_tag_home_path(tag: tag.name) %>
                </li>
                <li>|</li>
              <% end %>
            </ul>

          </div>
        </div>
        <div class="guanggao1"><img src="/assets/gg1.gif" /></div>
        <div class="box3_right_1k">
          <div class="box1_right_xia_top"><span class="box1_right_xia_topzi1"><strong><%= @keyword %>企业报价</strong></span></div>
          <div class="box3_right_1k_xia">
            <ul>
              <% @company_prices.each do |company_price| %>
                <li>
                  <%= link_to truncate(company_price.name, length: 10), company_price, title: company_price.name %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="clear"></div>
    </div>


  <% else %>


    共有<%= @transactions.total_entries.size %>条关于<%= @keyword %>的信息
    <br/>

    <% [["全部信息", nil], ["供应信息", "supply"], ["求购信息", "seeking"]].each do |info| %>
      <%= link_to info[0], search_home_path(category: info[1], keyword: @keyword, region_id: @region_id, refreshed_at: @refreshed_at) %>
    <% end %>
    <br/>

    <%= form_tag search_home_path, method: "get" do %>
      <%= hidden_field_tag "category", @category %>
      <%= select_tag "region_id", options_for_select(Region.all.map{|r| [r.name, r.id]}, @region_id), prompt: "请选择一个省份" %>
      <%= select_tag "refreshed_at", options_for_select([["1天内", 1], ["3天内", 3], ["一周内", 7], ["一个月内", 30], ["两个月内", 60]], @refreshed_at), prompt: "请选择发布时间" %>
      调整关键字: <%= text_field_tag "keyword", @keyword %>
      <%= submit_tag "筛选" %>
    <% end %>

    <br/>

    <% Transaction.top_tags(30).each do |tag| %>
      <%= link_to tag.name, search_by_tag_home_path(tag: tag.name) %>
    <% end %>

    <% @transactions.each do |t| %>
      <%= link_to (head_image t, width: 50, height: 50), t, target: "_blank" %>
      <%= l t.refreshed_at.to_date %>
      <%= link_to t.title, t, target: "_blank" %>
      <%= t.desc %>
      <%= link_to t.user.company_name, website_path(t.user), target: "_blank" %>
      <%= t.user.suozaidi %>
      <%= t.user.member_text %>
      <%= t.price_by_unit %>
      <%= link_to "给我留言", website_path(t.user, category: "message"), target: "_blank" %>
      <%= link_to "联系方式", website_path(t.user, category: "contact"), target: "_blank" %>
      <%= link_to "门市部", website_path(t.user), target: "_blank" %>
      <hr/>
    <% end %>

    <%= will_paginate @transactions %>

  <% end %>

  <script text="type/javascript">
    $(function(){
      var category = "<%= params[:category] %>"
      switch(category){
        case "": $(".bar div").eq(0).addClass("fbg1");break;
        case "supply": $(".bar div").eq(1).addClass("fbg2");break;
        case "seeking": $(".bar div").eq(2).addClass("fbg2");break;
        default: $(".bar div").eq(0).addClass("fbg1");break;
      }
    })
  </script>