config/routes.rb
Resources::Application.routes.draw do

  resources :hangqingbaojias, only: [:index] do
    collection do 
      get "jiage_list"
      get "more_jiage_list"
      get "hangqing_list"
      get "dongtai_list"
      get "more_dongtai_list"
      get "comment"
    end
  end

  resources :jiages do 
    collection do 
      get "get_categories"
    end
  end

  resources :dongtais

  resources :hangqings

  resources :comments do
    collection do 
      get "list"
    end
  end

  resources :contacts

  resources :message_types

  resources :lanzis, only: [:index, :create, :destroy]

  resources :customer_types

  resources :customers

  resources :news

  resources :transaction_types

  resources :shangjidingzhis do 
    collection do
      get "list"
    end
  end

  resources :company_prices
  resources :jiaoyis, only: [:index, :show]
  resources :baojias, only: [:index]
  resources :hangqingbaojias, only: [:index]
  resources :zixuns, only: [:index] do 
    collection do
      get "list"
    end
  end

  get "home" => "home#index"
  get "shangbiao" => "home#shangbiao"
  get "shengming" => "home#shengming"
  get "services" => "home#services"
  get "privacy" => "home#privacy"
  get "ad" => "home#ad"
  get "lianxi" => "home#lianxi"
  get "recruit" => "home#recruit"
  get "guanggao_attachment" => "home#guanggao_attachment"
  get "search_home" => "home#search"
  get "search_by_tag_home" => "home#search_by_tag"
  get "admin" => "admin#index"

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  devise_scope :user do
    get "bianji_mima", :to => "devise/registrations#bianji_mima"
    put "update_password", :to => "devise/registrations#update_password"
  end

  resources :regions, only: [:show]

  resources :countries, only: [:show]

  get 'verify_email_exist' => "users#verify_email_exist"
  get 'verify_username_exist' => "users#verify_username_exist"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get "entverify"
      put "verify"
      get "purview"
      get "entmember"
      put "member"
      get "home"
      get "info_and_image"
      get "edit_desc"
      put "update_desc"
      get "edit_image"
      get "edit_license"
    end
  end

  resources :transactions do
    member do
      get "images"
    end

    collection do
      get "tags"
      get "refresh"
    end

    member do
      get "change_transaction_type"
    end
  end

  delete "delete_transactions" => "transactions#destroy"

  resources :links

  resources :attachments do
    collection do
      post "upload"
    end
  end

  resources :categories, only: :show
  resources :company_price_categories, only: :show
  resources :articles
  resources :messages do
    collection do
      put "restore"
    end
  end

  constraints(Subdomain) do
    match '/' => 'member#home', as: "member_home"
    match '/member/show' => 'member#show'
    match '/member/contact' => 'member#contact'
    match '/member/transactions' => 'member#transactions'
    match '/member/transaction/:id' => 'member#transaction', as: "member_transaction"
    match '/member/news' => 'member#news'
    match '/member/message' => 'member#message'
    match '/member/news/:id' => 'member#new', as: "member_new"
  end

  root to: "home#index"

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:error).call(env) }  # 因为application.rb捕获不到rails路由错误，所以rails路由报错后指向application_controller.rb中的error action.

end

app/models/transaction_type.rb
#coding: utf-8

class TransactionType < ActiveRecord::Base

  belongs_to :user
  has_many :transactions, dependent: :nullify

  validates :name, presence: true, length: {maximum: 20}
  validates :desc, length: {maximum: 1000}

end

app/controllers/transactions_controller.rb
# coding: utf-8

class TransactionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :tags]
  before_filter :filter_tag_list, only: [:create, :update]
  after_filter :save_images, only: :create

  layout "admin", except: [:show]

  def index
    @search = current_user.transactions.search(params[:search])
    @transactions = @search.page(params[:page]).per_page(15).order("refreshed_at DESC")
  end

  def new
    @transaction = current_user.transactions.new(info_type: params[:info_type] || "supply" )
    @transaction.attachments.new
  end

  def edit
    @transaction = current_user.transactions.find(params[:id])
  end

  def show
    @transaction = Transaction.find(params[:id])
    @user = @transaction.user
    @transactions = @user.transactions.order("created_at DESC").page(params[:page]).per_page(10)
    @xg_transactions = Transaction.search({category2_id_eq: @transaction.category2_id}).order("created_at DESC").limit(10)
  end

  def create 
    @transaction = current_user.transactions.new(params[:transaction])
    if @transaction.save
      redirect_to transactions_path
    else
      render :new
    end
  end

  def update
    @transaction = current_user.transactions.find(params[:id])
    if @transaction.update_attributes(params[:transaction])
      redirect_to transactions_path
    else
      render :edit
    end
  end

  def destroy
    transaction = current_user.transactions.where(id: params[:id])
    transaction.destroy_all
    
    redirect_to transactions_path(search: params[:search])
  end

  def images
    @transaction = current_user.transactions.find(params[:id])
  end

  def tags  
    @tag_name, @transactions = params[:name], Transaction.tagged_with(params[:name]).page(params[:page]).per_page(50).order("created_at DESC")
  end

  def change_transaction_type
    transaction = current_user.transactions.find(params[:transaction_id])
    transaction.update_attribute(:transaction_type_id, params[:transaction_type_id])
    render nothing: true
  end

  def save_images
    if params["image_ids"].present?
      Attachment.where("id in (?)", params["image_ids"].split(",")).update_all(transaction_id: @transaction.id)
    end
  end

  def refresh
    transactions = current_user.transactions.where(id: params[:id])
    now = Time.now
    transactions.each do |t|
      t.update_attributes(refreshed_at: now)
    end
    if request.xhr?
      render json: {refreshed_at: I18n.l(now)}
    else
      redirect_to transactions_path(search: params[:search])
    end
  end

  def filter_tag_list
    params[:transaction][:tag_list] = params[:transaction][:tag_list].values.join(",")
  end

end

app/helpers/transactions_helper.rb
# coding: utf-8

module TransactionsHelper

  def transaction_title(info_type)
    case info_type
    when nil then "供求信息列表"
    when "supply" then "供应信息列表"
    when "seeking" then "求购信息列表"
    end
  end

  def transaction_price(transaction)
    transaction.price + transaction.price_unit + "/" + transaction.quantity_unit
  end

  def transaction_quantity(transaction)
    "#{transaction.quantity} #{transaction.quantity_unit}" if transaction.quantity?
  end

  def transaction_provide_quantity(transaction)
    transaction.provide_quantity.to_s + transaction.quantity_unit
  end

  def quantity_unit_other(transaction, quantity_unit)
    if transaction.new_record?
      ["吨", "千克", "斤"].include?(quantity_unit) ? "" : quantity_unit
    else
      ["吨", "千克", "斤"].include?(transaction.quantity_unit) ? "" : transaction.quantity_unit
    end
  end

  def price_unit_other(transaction, price_unit)
    if transaction.new_record?
      ["元", "美元"].include?(price_unit) ? "" : price_unit
    else
      ["元", "美元"].include?(transaction.price_unit) ? "" : transaction.price_unit
    end
  end




end

app/views/transactions/edit.html.erb
<%= title "编辑供求信息" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">编辑供求信息</div>
  <div class="fbxx_imt">
    <strong>重要提醒：</strong>请您务必确认您所发布的信息真实、合法、准确、及时，未侵犯他人合法权利，以免引致不必要的纠纷!
  </div>
  <%= render "form" %>
</div>
<div class="clear"></div>

<script text="type/javascript">
  $(function(){
    $("#transactions").addClass("ht_dianji")
  })
</script>

app/views/transactions/images.html.erb
<div class="gly_bottom_right">
  <div class="gly_right_header"></div>
  <div class="ht_bot">
    <div class="fbxx_top">上传<%= current_user.company_name %>的图片</div>
    <div class="fbxx_footer">
      <ul>
        <% @transaction.attachments.each do |attachment| %>
          <div class="aaa">
            <div class="aaa_pic">
              <%= image_tag attachment.image.url, width: 110, height: 95 %>
            </div>
            <div class="center_text">
              <%= link_to "删除", attachment_path(attachment), method: :delete, class: "centeranniu" %>
            </div>
          </div>
        <% end %>
        <li class="wrong_text">
        <%= flash[:error_messages].try(:join, ",") %>
        </li>
      </ul>
      <%= simple_form_for Attachment.new, path: attachments_path, multiple: true do |f| %>
        <%= f.input :transaction_id, as: :hidden, label: false, wrapper: false, input_html: {value: @transaction.id} %>
        <ul>
          <li class="fbxx_footer_zi4">在此上传图片：</li>
          <li>
          <%= f.input :image, as: :file, label: false, wrapper: false, input_html: {class: "wenjianyu1"} %>
          </li>
          <li>
          <%= f.submit "上传", class: "anniu17" %>
          </li>
        </ul>
        <ul>
        </ul>
        <ul>
          <li class="ht_qyjj_xgpic_text"><font color="#FF6600">提示：</font>所选图片都必须是jpg、gif、png、jpeg或bmp格式，图片的大小不得超过2M</li>
        </ul>
      <% end %>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/transactions/index.html.erb
<%= title transaction_title(params[:search].try(:[], :info_type_eq)) %>

<div class="gly_bottom_right">
  <div class="gly_right_header">管理供求信息</div>
  <div class="glgq_k1">
    <ul>
      <li class="glgq_zi1">教您如何修改信息，如何争取排名更靠前：</li>
      <li class="glgq_zi2">修改：仅修改信息内容</li>
      <li class="glgq_zi2">刷新：信息内容保持不变，仅更新发布时间，让您的信息排名靠前，高级会员每隔半小时可刷新一次，普通会员每天限刷新一次！</li>
    </ul>
  </div>
  <div class="glgq_k2"><%= link_to "全部(#{current_user.transactions.size})", transactions_path %> | <%= link_to "未过期(#{current_user.transactions.valid.size})", transactions_path({search: {is_valid_eq: true}}) %> | <%= link_to "已过期(#{current_user.transactions.invalid.size})", transactions_path({search: {is_valid_eq: false}}) %> </div>
  <%= form_tag delete_transactions_path, method: "delete", id: "form" do %>
    <%= hidden_field_tag "search[is_valid_eq]", params[:search].try(:[], :is_valid_eq) %>
    <div class="glgq_xia">
      <div class="glgq_xia_top">
        <ul>
          <span class="fuxuank4">
            <%= check_box_tag "select_all", '', false %>
          </span>
          <li class="glgq_xia_zi1_new"><strong>刷新</strong></li>
          <li class="glgq_xia_zi1"><strong>标题</strong></li>
          <li class="glgq_xia_zi2"><strong>刷新时间</strong></li>
          <li class="glgq_xia_zi2"><strong>发布时间</strong></li>
          <li class="glgq_xia_zi2"><strong>操作</strong></li>
        </ul>
      </div>
      <div class="glgq_xia_bot">
        <% @transactions.each do |transaction| %>
          <ul>
            <span class="fuxuank4">
              <%= check_box_tag "id[]", transaction.id, false, class: 'transaction_id' %>
            </span>
            <li class="glgq_xia_zi1_new">
            <% if transaction.can_refresh? %>
              <%= image_tag "refresh.gif" %>
              <%= link_to "刷新", "javascript:void(0)", value: transaction.id, class: "refresh" %>
            <% else %>
              最新
            <% end %>
            </li>
            <li class="glgq_xia_zi1">
            <%= link_to truncate(transaction.name, length: 15), transaction, title: transaction.name %>
            </li>
            <li class="glgq_xia_zi2 refreshed_at">
            <%= l transaction.refreshed_at %>
            </li>
            <li class="glgq_xia_zi2">
            <%= l transaction.created_at %>
            </li>
            <li class="glgq_xia_zi2">
            <%= link_to "编辑", edit_transaction_path(transaction) %> | <%= link_to "图片", images_transaction_path(transaction) %> | 
            <%= link_to "删除", transaction, method: :delete, confirm: "确定删除吗?" %>
            </li>
          </ul>
        <% end %>

      </div>
    </div>
  <% end %>

  <div class="glgq_xia_bot_k">
    <ul>
      <li><%= button_tag "刷新", id: "refresh" %></li>
      <li><%= button_tag "删除", id: "delete" %></li>
      <li><%= button_tag "一键刷新", id: "refresh_all" %></li>
    </ul>
  </div>
  <%= will_paginate @transactions %>
</div>
<div class="clear"></div>


<script type="text/javascript">
  $(function(){

    var category = "<%= params[:search].try(:[], :is_valid_eq) %>"
    switch(category){
      case "": $(".glgq_k2 a").eq(0).addClass("ppp");break;
      case "true": $(".glgq_k2 a").eq(1).addClass("ppp");break;
      case "false": $(".glgq_k2 a").eq(2).addClass("ppp");break;
      default: $(".glgq_k2 a").eq(0).addClass("ppp");break;
    }

    $(".glgq_k2 a").bind("click", function(){
      $(".glgq_k2 a").removeClass("ppp")
      $(this).addClass("ppp")
    })

    $("#transactions").addClass("ht_dianji")

    $(".refresh").click(function(){
      link = $(this)
      $.get("<%= refresh_transactions_path %>", {id: link.attr("value")}, function(data){
        if("<%= params['search'] && (params['search']['is_valid_eq'] == 'false') %>" == "true"){
          link.parents("ul").hide()
        }else{
          link.parents("li").next().next().text(data["refreshed_at"])
          link.parent().text("最新")
        }
      })
    })

    $("#select_all").change(function(){
      $(".transaction_id").attr("checked", $(this).prop("checked"))
    })

    $("#refresh").click(function(){
      if($(".transaction_id:checked").length > 0){
        $("#form").attr("method", "get")
        $("#form").attr("action", "<%= refresh_transactions_path %>")
        $("#form").submit()
      }
    })

    $("#refresh_all").click(function(){
      $(".transaction_id").attr("checked", true)
      $("#form").attr("method", "get")
      $("#form").attr("action", "<%= refresh_transactions_path %>")
      $("#form").submit()
    })

    $("#delete").click(function(){
      if(confirm("确认要删除吗？")){
        if($(".transaction_id:checked").length > 0){
          $("#form").submit()
        }
      }
    })

  })
</script>

app/views/transactions/new.html.erb
<%= title "发布供求信息" %>

<div class="gly_bottom_right">
  <div class="gly_right_header">发布供求信息</div>
  <div class="fbxx_imt">
    <strong>重要提醒：</strong>请您务必确认您所发布的信息真实、合法、准确、及时，未侵犯他人合法权利，以免引致不必要的纠纷!
  </div>
  <%= render "form" %>
</div>
<div class="clear"></div>


<script text="type/javascript">
  $(function(){
    $("#left_new_transaction").addClass("ht_dianji")
  })
</script>

app/views/transactions/show.html.erb
<%= title @transaction.name %>

<div class="weizhi">当前位置：首页 >  交易中心 &gt; 供求信息 &gt; <font color="#FF6600">产品信息</font></div>
<div class="cpxx_header">
  <div class="cpxx_header_top">
    <div class="cpxx_header_top_left">[<%= @transaction.info_type_text %>]<%= @transaction.title %></div>
    <div class="cpxx_header_top_right"><%= @user.member_text %></div>
  </div>
  <div class="cpxx_header_bot">
    <div class="cpxx_header_bot_k1">
      <div class="cpxx_header_bot_k1_l">
        <ul>
          <li class="cpxx_header_bot_k1_pic">
          <%= head_image @transaction, width: 252, height: 284, class: "medium" %>
          </li>
          <% @transaction.attachments.each do |atta| %>
            <li class="cp_smallpic">
              <%= image_tag atta.image.url(:medium), width: 46, height: 33, class: "thumb" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="cpxx_header_bot_k1_r">
        <ul>
          <li class="cpxx_header_bot_k1_zi2"><%= @transaction.info_type_text %>价格：<%= @transaction.price_by_unit %></li>
          <li class="cpxx_header_bot_k1_zi2"><%= @transaction.info_type_text %>数量：<font color="#cc0000"><strong><%= @transaction.provide_quantity_by_unit %></strong></font></li>
          <li class="cpxx_header_bot_k1_zi2"><%= @transaction.info_type_text %>总量：<font color="#cc0000"><strong><%= @transaction.provide_quantity_by_unit %></strong></font></li>
          <li class="cpxx_header_bot_k1_zi2"><%= @transaction.info_type_text %>情况：<%= @transaction.provide_statu_text %></li>
          <li class="cpxx_header_bot_k1_zi2">所在地：<%= @transaction.location %></li>
          <li class="cpxx_header_bot_k1_zi2">发布日期：<%= l @transaction.created_at.to_date %></li>
          <li class="cpxx_header_bot_k1_zi2">信息有效期：<%= @transaction.youxiaoqi %></li>
          <li class="cpxx_header_bot_k1_zi3">
          <% @transaction.tag_list.each do |tag| %>
            <%= link_to tag, search_by_tag_home_path(tag: tag) %>
          <% end %>
          </li>
          <%= link_to "加入篮子", lanzis_path(transaction_id: @transaction.id), method: :post, target: "_blank", class: "anniu5", style: "background:url(/assets/anniu3.gif)" %>
        </ul>
      </div>
    </div>
    <div class="cpxx_header_bot_k2">
      <div class="cpxx_header_bot_k2_top">
        <%= @user.company_name %>
      </div>
      <div class="cpxx_header_bot_k2_xia">
        <div class="cpxx_header_bot_k2_anniu">
          <a href="<%= website_path(@user) %>"  target="_blank"><img src="/assets/cpxxanniu1.gif" border="0"/></a> 
        </div>
        <% if @user.is_have_website? %>
          <div class="cpxx_header_bot_k2_zi1">
            <a href="<%= website_path(@user, category: "transactions") %>" target="_blank">最新供求</a> | <a href="<%= website_path(@user, category: "show") %>" target="_blank">公司介绍</a>
          </div>
        <% end %>
        <ul>
          <li>联系人：<%= @user.call %></li>
          <li>电 话： <%= @user.phone %></li>
          <li>传 真：<%= @user.fax %></li>
          <li>邮 箱：<%= @user.email %></li>
          <li>地 址：<%= @user.address %>(<%= @user.suozaidi %>)</li>
          <li>邮 编：<%= @user.zip_code %></li>
          <li>网 址：<%= link_to_if @user.company_url, @user.company_url, @user.company_url %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="cpxx_bottom">
  <div class="cpxx_bottom_left">
    <div class="cpxx_bottom_left_k1">
      <div class="cpxx_bottom_left_top">
        <ul>
          <li class="cpxx_bottom_left_bt1">详细信息</li>
          <li class="cpxx_bottom_left_bt2"></li>
        </ul>
      </div>
      <div class="cpxx_bottom_left_xia">
        <%= @transaction.desc %>
      </div>
    </div>
    <div class="cpxx_bottom_left_k1">
      <div class="cpxx_bottom_left_top">
        <ul>
          <li class="cpxx_bottom_left_bt3">该商家信息</li>
          <li class="cpxx_bottom_left_bt4"></li>
        </ul>
      </div>
      <div class="cpxx_bottom_left_xia2">
        <% @transactions.each do |t| %>
          <ul>
            <div class="cpxx_bottom_left_xia2_pic">
              <%= head_image(t, width: 114, height: 105) %>
            </div>
            <li class="cpxx_bottom_left_xia2_zi">
            <%= link_to truncate(t.name, length: 12), t, title: t.name %>
            </li>
          </ul>
        <% end %>
        <%= will_paginate @transactions %>
      </div>
    </div>
    <div class="cpxx_bottom_left_k1">
      <div class="cpxx_bottom_left_top">
        <ul>
          <li class="cpxx_bottom_left_bt1">在线留言</li>
          <li class="cpxx_bottom_left_bt2"></li>
        </ul>
      </div>
      <%= simple_form_for Message.new, html: {class: "validate_form"} do |f| %>
        <%= hidden_field_tag "liuyan", "yes" %>
        <%= f.input :to_id, as: "hidden", input_html: {value: @user.id}, label: false, wrapper: false %> 
        <div class="cpxiak">
          <span class="error"><%= flash[:alert] %></span>
          <span class="tishixinxi"><%= flash[:notice] %></span>
          <div class="gt_cp_lytopk">
            <div class="gly_fbwz_zi1">标题：</div>
            <%= f.input :title, input_html: {value: "我对#{@transaction.category_name}感兴趣", class: "validate[required] wenben7"}, label: false, wrapper: false %>
          </div>
          <div class="cp_k2">
            <div class="cp_text">内容：</div>
            <%= f.input :desc, input_html: {class: "validate[required, maxSize[1500]] cp_wenbenyu"}, label: false, wrapper: false %>
            <input name="" type="submit" class="cp_button" value="提交留言" />
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="cpxx_bottom_right">
    <div class="cpxx_bottom_right_k2">
      <div class="cpxx_bottom_right_k2_top">相关产品</div>
      <div class="cp_right_fot">
        <ul>
          <% @xg_transactions.each do |t| %>
            <li class="cp_right_fot_zi1">
            ·<%= link_to truncate(t.name, length: 15), t, title: t.name %>
            </li>
            <li class="cp_right_fot_zi2"><%= l t.created_at.to_date %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>

  <script text="type/javascript">
  $(function(){
    $(".thumb").click(function(){
      $(".medium").attr("src", $(this).attr("src"))
    })
  })
</script>

app/views/transactions/tags.html.erb
<h1>标签<%= @tag_name %></h1>
<%= title @tag_name %>

<table>
  <tr>
    <th>标题</th>
    <th>发布时间</th>
    <th>操作</th>
  </tr>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= link_to transaction.name, transaction %></td>
      <td>
        <% if transaction.can_refresh? %>
          <%= link_to "刷新", "javascript:void(0)", value: transaction.id, class: "refresh" %>
        <% else %>
          已是最新
        <% end %>
      </td>
      <td><%= l transaction.refreshed_at %></td>
      <td><%= l transaction.created_at %></td>
      <td>
        <%= link_to "编辑", edit_transaction_path(transaction) %>
        <%= link_to "图片", images_transaction_path(transaction) %>
        <%= link_to_if current_user && transaction.user == current_user, "删除", transaction_path(transaction), method: :delete, confirm: "确定删除吗?" %>
      </td>  
    </tr>
  <% end %>

</table>

<%= will_paginate @transactions %>